[package]
name = "vulkan-tutorial"
version = "1.0.0"
edition = "2021"
authors = ["Lyrapuff <lyrapuff@gmail.com>"]

[dependencies]
ash = { version = "0.35.0", default-features = false, features = ["linked", "debug"] }
winit = "0.26.1"