[package]
name = "vulkan-tutorial"
version = "1.0.0"
edition = "2021"
authors = ["Lyrapuff <lyrapuff@gmail.com>"]

[dependencies]
vulkano = "0.27.1"
vulkano-win = "0.27.1"
vulkano-shaders = "0.27.1"

winit = "0.25.0"

nalgebra-glm = "0.5.0"